### ISSUE TITLE
Where to get the pretrained weights(e.g., res50, vgg16)?

### ISSUE THREAD

**Issue by miznchimaki** [Tung-I/Dual-awareness-Attention-for-Few-shot-Object-Detection#14]
Thanks for your great work! Now I want to reproduce  your few shot object detection resuls, but I don't know where teo download the pretrained weights(e.g., res50, vgg16) which are described in README.md. Can you provide me an url?

**Comment by Tung-I** [comment]
Hi, you can find some instructions in this repo: https://github.com/rbgirshick/py-faster-rcnn#beyond-the-demo-installation-for-training-and-testing-models. Actually, pretrained res50 and vgg16 are available everywhere, your can leverage the pretrained weights from other resources as well.

**Comment by miznchimaki** [comment]
> Hi, you can find some instructions in this repo: https://github.com/rbgirshick/py-faster-rcnn#beyond-the-demo-installation-for-training-and-testing-models. Actually, pretrained res50 and vgg16 are available everywhere, your can leverage the pretrained weights from other resources as well.

OK, thanks, I'll try as you told me
