### ISSUE TITLE
Some question about training.

### ISSUE THREAD

**Issue by G-gusle** [Tung-I/Dual-awareness-Attention-for-Few-shot-Object-Detection#4]
First of all, thank you for sharing the code.

I'd like to get a question about training.

1. Use the coco2014 dataset. I'm training, but it takes too much time. I use one GPU (TITAN Xp), which lasted five days. Does it usually take this long? (Iter is 34468)

2. If the method of 1 is wrong, can you tell me what is wrong?

3. Lastly, can I use more than two GPUs?

I'm a beginner, so the question may be strange, but please answer. :D

**Comment by Tung-I** [comment]
Well, I am not sure what kind of problem you have encountered. I assume you mean the program never stops training? The number of epoch (or iteration) will depend on several factors such as the learning rate you adopt. You can just terminate the program when the training seems to be converged.

**Comment by michaelku1** [comment]
> First of all, thank you for sharing the code.
> 
> I'd like to get a question about training.
> 
> 1. Use the coco2014 dataset. I'm training, but it takes too much time. I use one GPU (TITAN Xp), which lasted five days. Does it usually take this long? (Iter is 34468)
> 2. If the method of 1 is wrong, can you tell me what is wrong?
> 3. Lastly, can I use more than two GPUs?
> 
> I'm a beginner, so the question may be strange, but please answer. :D

1. COCO is a large dataset, so it's normal that it takes a long time to train, considering the scale of the DAnA model. Iteration number is large because you may be using a small batch size, but having too large a batch will make your cuda go out of memory, so as Tung suggested, you may want to consider training just number of iterations only.

2. There is nothing wrong training with different data splits.

3. Obviously you can, why do you think people buy more than one GPU for training their model :)?

**Comment by G-gusle** [comment]
> > First of all, thank you for sharing the code.
> > I'd like to get a question about training.
> > 
> > 1. Use the coco2014 dataset. I'm training, but it takes too much time. I use one GPU (TITAN Xp), which lasted five days. Does it usually take this long? (Iter is 34468)
> > 2. If the method of 1 is wrong, can you tell me what is wrong?
> > 3. Lastly, can I use more than two GPUs?
> > 
> > I'm a beginner, so the question may be strange, but please answer. :D
> 
> 1. COCO is a large dataset, so it's normal that it takes a long time to train, considering the scale of the DAnA model. Iteration number is large because you may be using a small batch size, but having too large a batch will make your cuda go out of memory, so as Tung suggested, you may want to consider training just number of iterations only.
> 2. There is nothing wrong training with different data splits.
> 3. Obviously you can, why do you think people buy more than one GPU for training their model :)?

 Thank you. I found the mGPUs option late. Thank you for answering my question.
After designating and turning 4 GPUs, 16 batches, the speed became very fast.
I am not good at English, so I write an answer with a translator.  :D

**Comment by IceHowe** [comment]
> 

Can you tell me how much time it takes to train a epoch on COCO when using one GPU and four GPUs respectively？
